---
title: "Candy Counting and the Crowd"
author: "Stephen Kaluzny"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Challenge

```{r load_packages, echo=FALSE}
suppressPackageStartupMessages(library("here"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("ggplot2"))
```

## The Data

```{r read_data}
guesses <- read.csv(here::here("data", "candyjar_guesses.csv"))
true_count <- read.csv(here::here("data", "candyjar_count.csv"))
```

```{r true_count}
Count <- true_count[, "Count", drop=TRUE]
names(Count) <- true_count[, "Type", drop=TRUE]
Count <- c(Count, Total=sum(Count))
```

The total number of pieces in the jar is
`r (Ans <- Count["Total"])`.

## The Winners

There were three groups playing this guessing game: Family, TIBCO (work) and
StatSoftFul (work alumni).

To compute the winners, we first compute the difference between each guess
and the answer, taking the absolute value.

```{r compute_differance}
guesses <- guesses %>% mutate(DiffAns = abs(Guess - Ans))
```


```{r winner_by_group}
guesses %>% group_by(Group) %>%
  summarise(Winner=Person[which.min(DiffAns)], MinDiff = min(DiffAns))
```
